package kereta2;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.nimbus.NimbusStyle;
import javax.swing.table.DefaultTableModel;


public class mainview extends javax.swing.JFrame {

    /**
     * Creates new form mainview
     */
    private void Kosongkan_Form(){
        txtkursi.setEditable(true);
        txtkursi.setText(null);
        txtnama.setText(null);
        txtjumlah.setText(null);
        txt_total.setText(null);
        txtbayar.setText(null);
        txtkembalian.setText(null);
        cbojurusan.setSelectedItem(null);
        cbojenis.setSelectedItem(null);
        txtharga.setText(null);
    }
    
    private void Tampilkan_Data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nomor");
        model.addColumn("Nomor Kursi");
        model.addColumn("Nama Penumpang");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Bayar");
        model.addColumn("Uang Bayar");
        model.addColumn("Uang Kembali");
        model.addColumn("Jurusan");
        model.addColumn("Jenis");
        model.addColumn("Harga");
        
        
        try {
            int no = 1;
            String sql = "SELECT * FROM tb_kereta2 where nomor_kursi like '%" + jButton6.getText()
                    +  "%'" + "or nama_penumpang like '%" + jButton6.getText()
                    +  "%'" + "or jumlah_beli '%" + jButton6.getText()
                    +  "%'" + "or total_bayar like '%" + jButton6.getText()
                    +  "%'" + "or uang_bayar like '%" + jButton6.getText()
                    +  "%'" + "or uang_kembali like '%" + jButton6.getText()
                    +  "%'" + "or jurusan like '%" + jButton6.getText()
                    +  "%'" + "or jenis like '%" + jButton6.getText()
                    +  "%'" + "or harga like '%" + jButton6.getText() + "%'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while (res.next()){
                model.addRow(new Object[]{no++, res.getString(1), res.getString(2), res.getString(3), res.getString(4),res.getString(5), res.getString(6), res.getString(7)});
            }
            table.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    public mainview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbojurusan = new javax.swing.JComboBox<>();
        cbojenis = new javax.swing.JComboBox<>();
        txtharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtkursi = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 98, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENCATATAN PENJUALAN TIKET KERETA API");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Kereta");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jurusan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");

        cbojurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Surabaya", "Yogyakarta", "Solo", "Semarang" }));
        cbojurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbojurusanActionPerformed(evt);
            }
        });

        cbojenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "(Surabaya)VIP", "(Surabaya)EKONOMI", "(Yogyakarta)VIP", "(Yogyakarta)EKONOMI", "(Solo)VIP", "(Solo)EKONOMI", "(Semarang)VIP", "(Semarang)EKONOMI" }));
        cbojenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbojenisActionPerformed(evt);
            }
        });

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nomor Kursi");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama Penumpang");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Beli");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Bayar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Uang Bayar");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Uang Kembali");

        txtkursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkursiActionPerformed(evt);
            }
        });

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
        });

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });

        txtkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembalianActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(202, 211, 200));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor_Kursi", "Nama_Penumpang", "Jumlah_Beli", "Total_Bayar", "Uang_Bayar", "Uang_Kembali", "Jurusan", "Jenis", "Harga"
            }
        ));
        table.setColumnSelectionAllowed(true);
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setSelectionBackground(new java.awt.Color(51, 204, 0));
        table.setShowGrid(true);
        table.setUpdateSelectionOnSort(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        table.getAccessibleContext().setAccessibleDescription("");

        jButton6.setBackground(new java.awt.Color(0, 98, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(82, 82, 82)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbojenis, 0, 271, Short.MAX_VALUE)
                                            .addComponent(cbojurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtharga))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(72, 72, 72))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jButton5)
                                        .addGap(125, 125, 125)
                                        .addComponent(jButton2)
                                        .addGap(141, 141, 141)
                                        .addComponent(Hapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(162, 162, 162)
                                        .addComponent(jButton1))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtkembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                        .addComponent(txtbayar)
                                        .addComponent(txt_total)
                                        .addComponent(txtjumlah)
                                        .addComponent(txtnama)
                                        .addComponent(txtkursi)))))
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbojurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtkursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbojenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(Hapus)
                    .addComponent(jButton5))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbojurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbojurusanActionPerformed
        // TODO add your handling code here:
        // kondisi untuk menentukan harga sesuai jurusasn
    if (cbojurusan.getSelectedItem().toString().equalsIgnoreCase("Surabaya")) {
    }else if (cbojurusan.getSelectedItem().toString().equalsIgnoreCase("Yogyakarta")) {
    }
    else if (cbojurusan.getSelectedItem().toString().equalsIgnoreCase("Solo")) {
    }
    else if (cbojurusan.getSelectedItem().toString().equalsIgnoreCase("Semarang")) {
    }
    }//GEN-LAST:event_cbojurusanActionPerformed

    private void cbojenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbojenisActionPerformed
        // TODO add your handling code here:
        if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Surabaya)VIP")) {
            txtharga.setText("80000");
        } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Surabaya)Ekonomi")) {
            txtharga.setText("40000");
        } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Yogyakarta)VIP")) {
            txtharga.setText("70000");
        } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Yogyakarta)Ekonomi")) {
            txtharga.setText("35000");
        } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Solo)VIP")) {
            txtharga.setText("60000");
        } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Solo)Ekonoomi")) {
            txtharga.setText("30000");
        } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Semarang)VIP")) {
            txtharga.setText("50000");
        } else if (cbojenis.getSelectedItem().toString().equalsIgnoreCase("(Yogyakarta)VIP")) {
            txtharga.setText("25000");
        }
    }//GEN-LAST:event_cbojenisActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtkursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkursiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkursiActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarActionPerformed

    private void txtkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembalianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        if (txtkursi.getText().trim().equals("") || txtnama.getText().trim().equals("") || txtjumlah.getText().trim().equals("") || txt_total.getText().trim().equals("") || txtbayar.getText().trim().equals("") || txtkembalian.getText().trim().equals("") || cbojurusan.getSelectedItem()== null || cbojenis.getSelectedItem()== null || txtharga.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Data yang anda masukan belum lengkap dan Silahkan Ulangi Kembali");
        } else {
        model.addRow(new Object[] {txtkursi.getText(), txtnama.getText(), txtjumlah.getText(), txt_total.getText(), txtbayar.getText(), txtkembalian.getText(), cbojurusan.getSelectedItem(), cbojenis.getSelectedItem(), txtharga.getText()});
        }
        try {
            String sql = " INSERT INTO tb_kereta2 VALUES ('" + txtkursi.getText()
                    + "','" + txtnama.getText()
                    + "','" + txtjumlah.getText()
                    + "','" + txt_total.getText()
                    + "','" + txtbayar.getText()
                    + "','" + txtkembalian.getText()
                    + "','" + cbojurusan.getSelectedItem()
                    + "','" + cbojenis.getSelectedItem()
                    + "','" + txtharga.getText()+ "')";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Proses Simpan Berhasil");
            Tampilkan_Data();
            Kosongkan_Form();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Kosongkan_Form();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        if (table.getSelectedRow() != -1){
            String kursi = txtkursi.getText();
            String nama = txtnama.getText();
            String beli = txtjumlah.getText();
            String bayar = txtbayar.getText();
            String kembali = txtkembalian.getText();
            String jurusan = cbojurusan.getSelectedItem().toString();
            String jenis = cbojenis.getSelectedItem().toString();
            String harga = txtharga.getText();
            
            // set updated value on table row
            model.setValueAt(kursi,table.getSelectedRow(),0);
            model.setValueAt(nama,table.getSelectedRow(),1);
            model.setValueAt(beli,table.getSelectedRow(),2);
            model.setValueAt(bayar,table.getSelectedRow(),3);
            model.setValueAt(kembali,table.getSelectedRow(),4);
            model.setValueAt(jurusan,table.getSelectedRow(),5);
            model.setValueAt(jenis,table.getSelectedRow(),6);
            model.setValueAt(harga,table.getSelectedRow(),7);
            
            //  updated message display
            JOptionPane.showMessageDialog(this,"Update Succesfully");
            
        } else {
            if (table.getRowCount() == 0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            } else {
                JOptionPane.showMessageDialog(this,"Please select Single Row");
            }
        }
        
        try {
            String sql = " UPDATE tb_kereta2 SET nomor_kursi='" + txtkursi.getText()
                    + "',nama_penumpang='" + txtnama.getText()
                    + "',jumlah_beli='" + txtjumlah.getText()
                    + "',total_bayar='" + txt_total.getText()
                    + "',uang_bayar='" + txtbayar.getText()
                    + "',uang_kembali='" + txtkembalian.getText()
                    + "',jurusan='" + cbojurusan.getSelectedItem()
                    + "',jenis='" + cbojenis.getSelectedItem()
                    + "',harga='" + txtharga.getText() 
                    + "'WHERE nomor_kursi='" + txtkursi.getText()+ "'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Edit Berhasil");
            Tampilkan_Data();
            Kosongkan_Form();        
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
DefaultTableModel model = (DefaultTableModel) table.getModel();

// delete row
if (table.getSelectedRowCount() == 1) {
    // if a single row is selected, then delete it
    int selectedRow = table.getSelectedRow();
    model.removeRow(selectedRow);
} else {
    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Table is Empty");
    } else {
        JOptionPane.showMessageDialog(this, "Please select a single row to delete");
    }
}

        try {
            String sql = " DELETE FROM tb_kereta2 WHERE nomor_kursi='" + txtkursi.getText()+ "'";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Hapus Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    Tampilkan_Data();
    Kosongkan_Form();     
    }//GEN-LAST:event_HapusActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a = Integer.valueOf(txtharga.getText());
        b = Integer.valueOf(txtjumlah.getText());
        c = a*b;
        txt_total.setText(""+c);
    }//GEN-LAST:event_txtjumlahKeyReleased

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a = Integer.valueOf(txtbayar.getText());
        b = Integer.valueOf(txt_total.getText());
        c = a - b;
        txtkembalian.setText(""+c);
    }//GEN-LAST:event_txtbayarKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    int baris = table.rowAtPoint(evt.getPoint());
    String Nomor_Kursi = table.getValueAt(baris,1).toString();
    txtkursi.setText(Nomor_Kursi);
    
    String Nama_Penumpang = table.getValueAt(baris,2).toString();
    txtkursi.setText(Nama_Penumpang);
    
    String Jumlah_Beli = table.getValueAt(baris,3).toString();
    txtkursi.setText(Jumlah_Beli);
    
    String Total_Bayar = table.getValueAt(baris,4).toString();
    txtkursi.setText(Total_Bayar);
    
    String Uang_Bayar = table.getValueAt(baris,5).toString();
    txtkursi.setText(Uang_Bayar);
    
    String Uang_Kembali = table.getValueAt(baris,6).toString();
    txtkursi.setText(Uang_Kembali);
    
    String Jurusan = table.getValueAt(baris,7).toString();
    txtkursi.setText(Jurusan);
    
    String Jenis = table.getValueAt(baris,8).toString();
    txtkursi.setText(Jenis);
    
    String Harga = table.getValueAt(baris,9).toString();
    txtkursi.setText(Harga);
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JComboBox<String> cbojenis;
    private javax.swing.JComboBox<String> cbojurusan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtkursi;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
